# Generated by Django 5.1.6 on 2025-05-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverinvite',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='caregiverinvite',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='caregiverinvite',
            name='transaction_id',
        ),
    ]
