from .base import *

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_RESULT_EXPIRES = 3600  # Task state expires after 1 hour
CELERY_TIMEZONE = 'Africa/Lagos'

REACT_FRONTEND_URL = 'http://localhost:5173'

EMAIL_USE_TLS=True
EMAIL_HOST=env('DEVELOPMENT_EMAIL_HOST')
EMAIL_HOST_USER=env('DEVELOPMENT_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=env('DEVELOPMENT_EMAIL_HOST_PASSWORD')
EMAIL_PORT=env('DEVELOPMENT_EMAIL_PORT')

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  
    "http://localhost:5174",  
    "http://localhost:5173",  
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # Allow JS to read CSRF token


SESSION_COOKIE_DOMAIN = "localhost"
CSRF_COOKIE_DOMAIN = "localhost"