# Generated by Django 5.1.6 on 2025-06-05 12:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
